--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/yt/Downloads/paranoid_android_hampus_olsson_2016_2556x1440.jpg"

-- Special
background="#0c1d21"
foreground="#c2c6c7"
cursor="#c2c6c7"

-- Colors
color0="#0c1d21"
color1="#3d94a9"
color2="#3571aa"
color3="#667daa"
color4="#848aa9"
color5="#a096a4"
color6="#aa7a82"
color7="#c2c6c7"
color8="#485558"
color9="#3d94a9"
color10="#3571aa"
color11="#667daa"
color12="#848aa9"
color13="#a096a4"
color14="#aa7a82"
color15="#c2c6c7"
